apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deepearthweatheralertsglobal
  namespace: '193736185683'
  selfLink: >-
    /apis/serving.knative.dev/v1/namespaces/193736185683/services/deepearthweatheralertsglobal
  uid: 7b4442fa-622e-4f59-9c39-9e2257a44883
  resourceVersion: AAYpnyMJACo
  generation: 38
  creationTimestamp: '2024-12-17T15:34:36.901959Z'
  labels:
    commit-sha: 41fba5c3c1aa5ea0b3c8d9ab7950431782aea721
    gcb-build-id: 71a173ea-8aa9-4924-b884-c8cb9cde75d4
    gcb-trigger-id: 83f04575-fe70-41a3-9008-4abbfed059e0
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    cloud.googleapis.com/location: europe-north1
  annotations:
    serving.knative.dev/creator: simon.vacher@gmail.com
    serving.knative.dev/lastModifier: simon.vacher@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: f47f9ca9-55a6-4b4a-ba2f-f0c84bda02d1
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: >-
      ["https://deepearthweatheralertsglobal-193736185683.europe-north1.run.app","https://deepearthweatheralertsglobal-4jqeqrqpja-lz.a.run.app"]
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 7c1caef5-2173-4c39-bddf-ba62b81f22ac
        commit-sha: 41fba5c3c1aa5ea0b3c8d9ab7950431782aea721
        gcb-build-id: 71a173ea-8aa9-4924-b884-c8cb9cde75d4
        gcb-trigger-id: 83f04575-fe70-41a3-9008-4abbfed059e0
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/logging-destination: logging
        run.googleapis.com/logging-level: INFO # Optional, change to INFO or WARNING
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 193736185683-compute@developer.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: >-
          europe-north1-docker.pkg.dev/deepearth-digital/cloud-run-source-deploy/weatheralertsglobal/deepearthweatheralertsglobal:41fba5c3c1aa5ea0b3c8d9ab7950431782aea721
        ports:
        - name: http1
          containerPort: 8080
        env:
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
